# Generated by Django 5.0.3 on 2024-03-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('desc', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='cat_img')),
            ],
        ),
    ]
